name: ells-landscaping
region: nyc

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

services:
  - name: web
    dockerfile_path: web/Dockerfile
    source_dir: /
    http_port: 3000
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb

    github:
      repo: colegil2012/exceptionalLandscaping
      branch: main
      deploy_on_push: true

    health_check:
      http_path: /
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      failure_threshold: 5

    termination:
      drain_seconds: 10
      grace_period_seconds: 20

    envs:
      - key: PUBLIC_API_BASE
        value: https://celtechsolutions.tech
        scope: RUN_TIME
      - key: PUBLIC_SITE_SLUG
        value: ells
        scope: RUN_TIME
      - key: NODE_ENV
        value: production
        scope: RUN_TIME

ingress:
  rules:
    - match:
        path:
          prefix: /
      component:
        name: web

domains:  # uncomment once you're ready to point DNS
  - domain: ells4u.com
    type: PRIMARY
  - domain: www.ells4u.com
    type: ALIAS